window.BRAND_CASES = [
  {
    slug: "poppi",
    date: "2026-09-10",
    brand: "Poppi",
    category: "功能汽水 / 消费品 / 全渠道",
    market: "美国 / 英国 / 国际扩张",
    tags: ["社交原生", "低糖汽水", "零售规模化"],
    summary: "Poppi 没把益生元汽水卖成一堂健康课，而是用经典口味、鲜艳罐身、创始人内容、创作者与全国零售，先恢复喝汽水的许可感，再用低糖和配方信息降低负担，把社交声量接到随处可买的日常选择。",
    insight: "功能消费品要进入主流，先保留旧品类的欲望与场景，再把功能证据压缩成降低犹豫的第二层信息，并让内容声量与实体可得性同步增长。",
    report: "reports/2026-09-10-poppi.html",
    accent: "#ff4f91",
    cover: ""
  },
  {
    slug: "hexclad",
    date: "2026-09-09",
    brand: "HexClad",
    category: "高端厨具 / DTC / 全渠道",
    market: "美国 / 加拿大 / 英国 / 欧洲 / 澳大利亚 / 日本 / 中东",
    tags: ["混合技术", "名厨信任", "演示型零售"],
    summary: "HexClad 用六边形混合表面、Gordon Ramsay 长期伙伴关系、演示内容、套装与授权零售，把家庭用户在不粘、铸铁与不锈钢之间的取舍，改写成一眼能懂、敢于试用并愿意整厨升级的高端厨具系统。",
    insight: "成熟品类的创新若难以解释，就把技术差异做成肉眼可见、动作可证的结构，再让权威、家庭达人、套装和线下演示分别承担信任、理解、客单与体验。",
    report: "reports/2026-09-09-hexclad.html",
    accent: "#db6f3d",
    cover: ""
  },
  {
    slug: "ridge",
    date: "2026-09-08",
    brand: "Ridge",
    category: "随身配件 / 消费硬件 / DTC",
    market: "美国 / 加拿大 / 英国 / 欧洲 / 澳大利亚",
    tags: ["英雄 SKU", "演示型内容", "终身保修"],
    summary: "Ridge 没把钱包继续卖成皮革与身份符号，而是用刚性双板、薄钱包演示、材料版本、99 天退货与终身保修，把“旧钱包还能用、升级又怕是智商税”的矛盾，改写成一场能被镜头证明、能被礼赠放大并向 EDC 延展的随身升级。",
    insight: "当成熟耐用品缺少换新理由时，先把旧方案的隐性摩擦拍成一帧，再让英雄结构、风险逆转和版本梯度分别承担理解、下单与客单增长。",
    report: "reports/2026-09-08-ridge.html",
    accent: "#5a7dff",
    cover: ""
  },
  {
    slug: "eight-sleep",
    date: "2026-09-07",
    brand: "Eight Sleep",
    category: "智能硬件 / 睡眠科技 / 订阅软件",
    market: "美国 / 欧洲 / 澳大利亚 / 中东 / 亚洲部分市场",
    tags: ["Sleep Fitness", "双区温控", "硬件订阅"],
    summary: "Eight Sleep 没把睡眠科技停在记录分数，而是用双区温控、Autopilot 夜间执行、晨间反馈、运动员内容与会员保修，把“睡眠越要无感、昂贵硬件越需证明价值”的矛盾改写成持续运行的恢复系统。",
    insight: "当高客单硬件还需要持续订阅时，首单价值必须由立刻可体验的物理变化承担，续费价值则要由自动执行、持续反馈和服务保障逐月兑现。",
    report: "reports/2026-09-07-eight-sleep.html",
    accent: "#3977ff",
    cover: ""
  },
  {
    slug: "who-gives-a-crap",
    date: "2026-09-06",
    brand: "Who Gives A Crap",
    category: "家清消费品 / DTC 订阅 / 社会企业",
    market: "澳大利亚 / 美国 / 英国 / 加拿大 / 欧洲",
    tags: ["幽默品牌化", "灵活订阅", "影响力消费"],
    summary: "Who Gives A Crap 没把环保厕纸卖成一堂道德课，而是先用厕所幽默、彩色包装、大箱单位成本、灵活订阅、推荐奖励和可核验的 50% 利润捐赠，把“高频刚需却只比价格”的低关注品类，改写成可展示、可复购、可传播的影响力消费系统。",
    insight: "当使命型产品同时面临溢价、信任和使用门槛时，先让产品体验、风险逆转和补货机制独立成立，再让可验证的社会影响成为复购与推荐的放大器。",
    report: "reports/2026-09-06-who-gives-a-crap.html",
    accent: "#ff6685",
    cover: ""
  },
  {
    slug: "canva",
    date: "2026-09-03",
    brand: "Canva",
    category: "设计 SaaS / 内容平台 / AI 工作流",
    market: "澳大利亚 / 美国 / 欧洲 / 全球",
    tags: ["模板入口", "创作者生态", "品牌管理"],
    summary: "Canva 没把设计软件卖成一套更专业的工具栈，而是先用模板、教程、创作者供给、Brand Kit 和 AI 工作流，把“每个团队都要做内容，但多数人既不会设计也不想先学软件”的矛盾，改写成一个先能发出来、再能团队化和品牌化扩张的全球内容生产系统。",
    insight: "当用户真正抗拒的不是价值，而是上手摩擦时，先把第一次产出做成几乎不需要训练的任务，再用模板复用、团队控制和 AI 压缩，逐层把免费动作升级成组织级预算。",
    report: "reports/2026-09-03-canva.html",
    accent: "#00c4cc",
    cover: ""
  },
  {
    slug: "duolingo",
    date: "2026-09-02",
    brand: "Duolingo",
    category: "教育 SaaS / 内容平台 / AI 学习产品",
    market: "美国 / 欧洲 / 拉美 / 全球",
    tags: ["角色内容", "免费转付费", "AI 升级"],
    summary: "Duolingo 没把语言学习卖成一门更严肃的课，而是先用角色内容、超短练习、连胜提醒、免费体验、Family Plan 和 Max，把“我知道该学，但总坚持不下去”的自律冲突，改写成一个更愿意天天回来、再逐步升级付费和 AI 辅导的学习平台。",
    insight: "当用户失败点不是不知道价值，而是每天回不来时，先把回访动作做轻、做短、做有人格，再把更顺滑的体验和更强反馈设计成逐级付费理由。",
    report: "reports/2026-09-02-duolingo.html",
    accent: "#58cc02",
    cover: ""
  },
  {
    slug: "manscaped",
    date: "2026-09-01",
    brand: "MANSCAPED",
    category: "男士个护 / 消费硬件",
    market: "美国 / 英国 / 加拿大 / 全球",
    tags: ["幽默品牌化", "会员积分", "全渠道分工"],
    summary: "MANSCAPED 没把男士体毛护理讲成一堂严肃的卫生课，而是先用带羞耻感的细分切口、统一命名、夸张幽默创意、套装承接、VIP 会员和 Amazon/零售积分回流，把“低参与、尴尬、只在临时需要时才想起”的男士个护，改写成一个能被记住、顺手下单并持续补货的全渠道品牌系统。",
    insight: "当用户不是没有需求，而是不想被认真教育时，先用文化语气和高记忆点帮他开口，再用套装、会员和跨渠道回流把关系真正留住。",
    report: "reports/2026-09-01-manscaped.html",
    accent: "#f58a3b",
    cover: ""
  },
  {
    slug: "jolie",
    date: "2026-08-31",
    brand: "Jolie",
    category: "美妆个护 / 家居硬件",
    market: "美国 / 加拿大",
    tags: ["新品类教育", "创作者种草", "滤芯订阅"],
    summary: "Jolie 没把过滤花洒卖成一件更高级的浴室五金，而是先用 Step Zero 叙事、Water Report 自查、创作者种草、滤芯订阅和 DTC/零售分工，把“总觉得护发护肤没效果，却不知道问题可能出在水”的模糊焦虑，改写成一个更容易理解、尝试、复购和顺手补货的美容硬件系统。",
    insight: "当你卖的是一个用户长期感受到结果、却没把原因归给你的问题时，先纠正错误归因，再用自查入口、低风险尝试和复购机制把新品类真正立住。",
    report: "reports/2026-08-31-jolie.html",
    accent: "#56c3d6",
    cover: ""
  },
  {
    slug: "lmnt",
    date: "2026-08-30",
    brand: "LMNT",
    category: "功能饮料 / 健康补给",
    market: "美国 / 加拿大",
    tags: ["权威内容", "订阅承接", "零售分工"],
    summary: "LMNT 没把电解质饮料讲成一瓶更甜的运动饮料，而是先用高钠无糖配方、创始人可信度、播客与社区推荐、INSIDER 订阅承接和 DTC/零售分工，把“我知道该补水，却不想再喝一堆糖和空洞功能词”的犹豫，改写成一个更容易被信任、复购和顺手补货的健康补给系统。",
    insight: "当品类教育和信任同时昂贵时，先别急着铺满渠道，先用一套鲜明主张和高可信内容把人群筛出来，再用订阅、推荐和零售承接。",
    report: "reports/2026-08-30-lmnt.html",
    accent: "#ff7440",
    cover: ""
  },
  {
    slug: "oura",
    date: "2026-08-27",
    brand: "Oura",
    category: "健康穿戴 / 智能硬件",
    market: "美国 / 欧洲 / 全球",
    tags: ["会员订阅", "口碑裂变", "零售扩张"],
    summary: "Oura 没把智能戒指卖成一块更小的手表，而是先用无屏佩戴、睡眠恢复分数、会员订阅、App AI 指导、口碑推荐和 Best Buy 零售承接，把“我想更懂身体但不想被设备打扰”改写成可长期续费的健康日常系统。",
    insight: "连续监测型硬件想做大众市场，先别堆更多实时提醒，先把复杂信号压缩成每天都能执行的一条建议，再把会员和口碑绑到同一条关系链里。",
    report: "reports/2026-08-27-oura.html",
    accent: "#7d88ff",
    cover: ""
  },
  {
    slug: "pura",
    date: "2026-08-11",
    brand: "Pura",
    category: "家居香氛 / 智能硬件",
    market: "美国",
    tags: ["硬件耗材一体", "订阅积分", "零售补货"],
    summary: "Pura 没把家居香氛停留在一次性礼物消费，而是先用智能扩香器、App 定时、洁净安全承诺、品牌香型合作、订阅积分和 Target / Amazon 渠道分工，把“偶尔想让家里好闻一点”的低频需求，改写成更容易尝试、复购和顺手补货的空间情绪系统。",
    insight: "当品类既需要溢价又需要复购时，先别卷单个 SKU，先把主机、耗材、软件和补货机制串成一条默认运行的关系链。",
    report: "reports/2026-08-11-pura.html",
    accent: "#76d0d7",
    cover: ""
  },
  {
    slug: "caraway",
    date: "2026-07-24",
    brand: "Caraway",
    category: "家居厨具",
    market: "美国",
    tags: ["非毒性叙事", "套装承接", "全渠道放大"],
    summary: "Caraway 没把厨具升级讲成一堂复杂的材料课，而是先用非毒性承诺、整套收纳、颜色审美、创作者长期合作、测验与套装承接，再配合 Target、Amazon 和 Walmart 等渠道分工，把“想换锅但嫌麻烦”的家庭决策改写成更容易理解、下单和放大的现代厨房系统。",
    insight: "高客单家庭耐用品别先卖参数，先把风险焦虑、空间秩序和审美表达压缩成一套人人能复述的升级理由，再用官网与零售分工接住。",
    report: "reports/2026-07-24-caraway.html",
    accent: "#d76c45",
    cover: ""
  },
  {
    slug: "bloom-nutrition",
    date: "2026-07-23",
    brand: "Bloom Nutrition",
    category: "女性健康消费品",
    market: "美国",
    tags: ["创作者飞轮", "组合装承接", "零售放大"],
    summary: "Bloom Nutrition 没把女性营养补剂讲成一堂难坚持的成分课，而是先用创始人转变叙事、好入口味、创作者自由脚本、组合装、积分和 Target / Walmart 扩张，把“总想变健康却总坚持不下去”改写成更容易尝试、复购和顺手补货的日常系统。",
    insight: "高频但难坚持的品类，先别加重教育负担，先把口感、情绪认同和创作者可复述性做好，再用官网关系资产和零售便利性接住。",
    report: "reports/2026-07-23-bloom-nutrition.html",
    accent: "#ff7cb1",
    cover: ""
  },
  {
    slug: "ruggable",
    date: "2026-07-20",
    brand: "Ruggable",
    category: "家居家装",
    market: "美国 / 英国 / 德国",
    tags: ["场景转译", "创作者营销", "零售承接"],
    summary: "Ruggable 没有先把地毯讲成昂贵的家居审美升级，而是先用可机洗、可替换结构、真实家庭内容、持续联名、首单优惠和 Target 等零售触点，把“怕脏怕后悔”的高客单决策改写成更敢买、更敢铺、也更容易复购的家装系统。",
    insight: "高客单耐用品要破圈，先别强化梦想画面，先把用户最怕的买后事故处理掉；用户一旦敢用，审美和联名才有增长价值。",
    report: "reports/2026-07-20-ruggable.html",
    accent: "#bd7d4f",
    cover: ""
  },
  {
    slug: "magic-spoon",
    date: "2026-07-14",
    brand: "Magic Spoon",
    category: "早餐消费品",
    market: "美国",
    tags: ["怀旧重写", "订阅承接", "零售放大"],
    summary: "Magic Spoon 没把高蛋白低糖麦片讲成自律早餐，而是先用童年口味、喜剧短视频、筛选型寄样、灵活订阅、限定口味和零售扩张，把一盒高价麦片改写成能被讨论、复购并走进货架的成年零食早餐品牌。",
    insight: "想卖贵的健康替代品，先别让用户感觉自己在牺牲；先把羞耻感改成怀旧快感，再用订阅和零售接住。",
    report: "reports/2026-07-14-magic-spoon.html",
    accent: "#6ec5ff",
    cover: ""
  },
  {
    slug: "liquid-death",
    date: "2026-07-12",
    brand: "Liquid Death",
    category: "饮料消费品",
    market: "美国 / 英国",
    tags: ["娱乐化品牌", "会员积分", "零售放大"],
    summary: "Liquid Death 没把水讲成更纯净的健康任务，而是先用重金属视觉、恶搞内容、merch、Skulls 积分、Amazon 补货、场馆合作和大零售铺货，把最无聊的饮用品类改写成一个能被讨论、被拿在手里、也能被持续复购的娱乐消费品牌。",
    insight: "越基础、越同质化的品类，越要先重写品类语气，再把官网、会员、零售和补货链路接成同一个世界观。",
    report: "reports/2026-07-12-liquid-death.html",
    accent: "#ff5a3d",
    cover: ""
  },
  {
    slug: "dr-squatch",
    date: "2026-07-10",
    brand: "Dr. Squatch",
    category: "个护消费品",
    market: "美国",
    tags: ["幽默创意", "订阅承接", "零售扩张"],
    summary: "Dr. Squatch 没把男士个护讲成一堂成分课，而是先用粗犷香型、夸张幽默、创作者段子、Starter Bundle、灵活订阅和零售扩张，把原本低参与的洗澡动作改写成更愿意尝试、送礼、讨论和复购的日常娱乐系统。",
    insight: "低参与品类破圈，先别教育用户变专业，先把他愿意开口谈、愿意试一次的入口做出来。",
    report: "reports/2026-07-10-dr-squatch.html",
    accent: "#8cc36f",
    cover: ""
  },
  {
    slug: "beis",
    date: "2026-07-08",
    brand: "BÉIS",
    category: "旅行用品",
    market: "美国",
    tags: ["功能演示", "创作者脚本", "零售分工"],
    summary: "BÉIS 没有把行李箱讲成更贵的专业装备，而是先抓住超重、鞋衣混装、随身包难挂和短途出行收纳混乱这些高频狼狈时刻，再用产品细节、Founder demo、pack-with-me 内容、快闪体验和 DTC/零售分工，把旅行用品做成更省脑也更愿意分享的出发系统。",
    insight: "高客单功能品要想破圈，先把用户最狼狈的 10 秒钟做成一眼能懂的解决方案，再让内容和渠道围绕它放大。",
    report: "reports/2026-07-08-beis.html",
    accent: "#f2c66d",
    cover: ""
  },
  {
    slug: "our-place",
    date: "2026-07-07",
    brand: "Our Place",
    category: "家居厨具",
    market: "美国",
    tags: ["英雄 SKU", "生活方式内容", "零售分工"],
    summary: "Our Place 没有把厨具讲成一整套专业配置，而是先用 Always Pan 这样的英雄单品压缩选择负担，再用色彩审美、菜谱内容、创作者厨房、套装升级和 DTC/零售分工，把下厨翻译成更愿意开始、分享和送礼的生活方式场景。",
    insight: "复杂耐用品破圈，往往先靠一个最省脑的英雄入口，再靠内容和渠道把它扩成整套生活方式。",
    report: "reports/2026-07-07-our-place.html",
    accent: "#e78d63",
    cover: ""
  },
  {
    slug: "blueland",
    date: "2026-07-06",
    brand: "Blueland",
    category: "家居清洁",
    market: "美国",
    tags: ["补充装系统", "环保转译", "零售放大"],
    summary: "Blueland 没有把环保清洁讲成牺牲与责任，而是用可重复使用的 Forever 瓶、补充片、套装承接、创作者推荐和 Target 放大，把“少用一次性塑料”翻译成更省脑、更顺手、也更容易坚持的家庭清洁习惯。",
    insight: "可持续品牌要想破圈，关键不是把理念讲得更重，而是把切换动作做得更轻、更默认。",
    report: "reports/2026-07-06-blueland.html",
    accent: "#6acfc7",
    cover: ""
  },
  {
    slug: "air-up",
    date: "2026-07-05",
    brand: "air up",
    category: "智能水具",
    market: "德国 / 英国 / 美国",
    tags: ["感官创新", "创作者种草", "全渠道习惯"],
    summary: "air up 没有把喝水讲成自律任务，而是用气味驱动的“有味白水”、反应型创作者内容、Starter Set 承接和零售铺货，把原本无聊的补水行为改造成更容易尝试、分享和复购的日常习惯。",
    insight: "当品类教育成本过高时，先把体验做成愿意试和愿意晒的行为，再用渠道把新奇感沉淀成习惯。",
    report: "reports/2026-07-05-air-up.html",
    accent: "#66d6df",
    cover: ""
  },
  {
    slug: "olipop",
    date: "2026-07-03",
    brand: "OLIPOP",
    category: "功能饮料",
    market: "美国",
    tags: ["怀旧口味", "创作者营销", "零售放大"],
    summary: "OLIPOP 没有把功能汽水讲成营养课，而是先保留怀旧口味、好看包装和想喝汽水的快乐，再用低糖高纤、创作者内容、订阅和零售覆盖把“更好替代”做成更容易试也更容易顺手买的日常选择。",
    insight: "更好替代型品牌要先守住原品类的快乐，再把功能、渠道和归因围绕这层快乐重组。",
    report: "reports/2026-07-03-olipop.html",
    accent: "#ff935c",
    cover: ""
  },
  {
    slug: "wild",
    date: "2026-07-02",
    brand: "Wild",
    category: "个护消费品",
    market: "英国 / 美国",
    tags: ["可持续包装", "订阅补货", "零售放大"],
    summary: "Wild 没有先把环保讲成责任，而是先把除臭剂做成愿意摆出来的生活方式配件，再用可换香型的 refill、可调订阅、联名内容和 Target 渠道把减塑行为变成更顺手的日常习惯。",
    insight: "可持续品牌破圈，往往不是靠说服用户牺牲，而是把更好的行为包装成更想要的升级体验。",
    report: "reports/2026-07-02-wild.html",
    accent: "#88d498",
    cover: ""
  },
  {
    slug: "hismile",
    date: "2026-07-01",
    brand: "Hismile",
    category: "口腔护理",
    market: "澳大利亚 / 全球",
    tags: ["感官重写", "联名内容", "套装承接"],
    summary: "Hismile 没有先把牙膏讲得更专业，而是用口味、颜色、联名和可拍的功效演示让用户愿意讨论刷牙，再用 V34、PAP+ 与 Starter Bundle 把尝鲜引向稳定的例行程序。",
    insight: "低参与度品类的增长，常常先来自更低的体验进入门槛，而不是更强的专业教育。",
    report: "reports/2026-07-01-hismile.html",
    accent: "#ff6aa7",
    cover: ""
  },
  {
    slug: "graza",
    date: "2026-06-30",
    brand: "Graza",
    category: "食品消费品",
    market: "美国",
    tags: ["场景命名", "包装创新", "创作者冷启动"],
    summary: "把复杂的橄榄油品质知识压缩成 Sizzle 与 Drizzle 两个厨房动作，再让挤压瓶同时承担使用体验、货架识别、短视频露出与补充装复购。",
    insight: "成熟品类的创新，常常不是增加知识，而是把选择压缩成一个直觉动作。",
    report: "reports/2026-06-30-graza.html",
    accent: "#d7ff45",
    cover: ""
  },
  {
    slug: "the-farmers-dog",
    date: "2026-06-29",
    brand: "The Farmer's Dog",
    category: "宠物鲜食",
    market: "美国",
    tags: ["DTC", "订阅制", "信任系统"],
    summary: "把鲜食的价格、冷链与换粮门槛拆成问卷、预分装、配送和生命周期触达，让“信任”成为产品的一部分。",
    insight: "高客单订阅的核心不是一次说服，而是持续降低每个履约节点的不确定感。",
    report: "reports/2026-06-29-the-farmers-dog.html",
    accent: "#f25f3a",
    cover: ""
  },
  {
    slug: "loop-earplugs",
    date: "2026-06-29",
    brand: "Loop Earplugs",
    category: "听力保护",
    market: "欧美",
    tags: ["场景重构", "创作者营销", "配件化"],
    summary: "把“隔绝噪音”改写成“留在现场”：用场景化声学产品、可识别耳饰造型和创作者测试闭环，把健康防护用品做成日常配件。",
    insight: "功能品破圈，常常从重新定义用户愿意公开表达的使用场景开始。",
    report: "reports/2026-06-29-loop-earplugs.html",
    accent: "#16a085",
    cover: ""
  },
  {
    slug: "owala",
    date: "2026-06-27",
    brand: "Owala",
    category: "保温水杯",
    market: "美国",
    tags: ["产品创新", "限量发售", "渠道独占"],
    summary: "用 FreeSip 消除“吸或灌”的行为冲突，再以配色、限量 Drop 和渠道独占，把耐用品变成身份配件。",
    insight: "固定英雄 SKU，用颜色与命名制造持续上新的理由。",
    report: "reports/2026-06-27-owala.html",
    accent: "#3478f6",
    cover: ""
  },
  {
    slug: "momcozy",
    date: "2026-06-26",
    brand: "Momcozy",
    category: "母婴护理",
    market: "欧美",
    tags: ["痛点创新", "KOC", "全渠道"],
    summary: "把吸奶器从医疗器械翻译成职场妈妈的自由感、隐私感和被理解感，并用真实妈妈内容建立信任。",
    insight: "不要先讲参数，先把功能翻译成用户重新获得的一段生活。",
    report: "reports/2026-06-26-momcozy.html",
    accent: "#d34f7a",
    cover: ""
  },
  {
    slug: "pop-mart",
    date: "2026-06-26",
    brand: "POP MART",
    category: "潮玩 IP",
    market: "全球",
    tags: ["IP", "稀缺感", "线下零售"],
    summary: "用 IP 稀缺感、社媒可晒性、线下仪式和全球履约，把小额潮玩做成跨市场情绪消费系统。",
    insight: "IP 的增长不只来自角色内容，还来自可重复参与的购买仪式。",
    report: "reports/2026-06-26-pop-mart.html",
    accent: "#ef3f55",
    cover: ""
  }
];
