window.BRAND_CASES = [
  {
    slug: "bloom-nutrition",
    date: "2026-07-23",
    brand: "Bloom Nutrition",
    category: "女性健康消费品",
    market: "美国",
    tags: ["创作者飞轮", "组合装承接", "零售放大"],
    summary: "Bloom Nutrition 没把女性营养补剂讲成一堂难坚持的成分课，而是先用创始人转变叙事、好入口味、创作者自由脚本、组合装、积分和 Target / Walmart 扩张，把“总想变健康却总坚持不下去”改写成更容易尝试、复购和顺手补货的日常系统。",
    insight: "高频但难坚持的品类，先别加重教育负担，先把口感、情绪认同和创作者可复述性做好，再用官网关系资产和零售便利性接住。",
    report: "reports/2026-07-23-bloom-nutrition.html",
    accent: "#ff7cb1",
    cover: ""
  },
  {
    slug: "ruggable",
    date: "2026-07-20",
    brand: "Ruggable",
    category: "家居家装",
    market: "美国 / 英国 / 德国",
    tags: ["场景转译", "创作者营销", "零售承接"],
    summary: "Ruggable 没有先把地毯讲成昂贵的家居审美升级，而是先用可机洗、可替换结构、真实家庭内容、持续联名、首单优惠和 Target 等零售触点，把“怕脏怕后悔”的高客单决策改写成更敢买、更敢铺、也更容易复购的家装系统。",
    insight: "高客单耐用品要破圈，先别强化梦想画面，先把用户最怕的买后事故处理掉；用户一旦敢用，审美和联名才有增长价值。",
    report: "reports/2026-07-20-ruggable.html",
    accent: "#bd7d4f",
    cover: ""
  },
  {
    slug: "magic-spoon",
    date: "2026-07-14",
    brand: "Magic Spoon",
    category: "早餐消费品",
    market: "美国",
    tags: ["怀旧重写", "订阅承接", "零售放大"],
    summary: "Magic Spoon 没把高蛋白低糖麦片讲成自律早餐，而是先用童年口味、喜剧短视频、筛选型寄样、灵活订阅、限定口味和零售扩张，把一盒高价麦片改写成能被讨论、复购并走进货架的成年零食早餐品牌。",
    insight: "想卖贵的健康替代品，先别让用户感觉自己在牺牲；先把羞耻感改成怀旧快感，再用订阅和零售接住。",
    report: "reports/2026-07-14-magic-spoon.html",
    accent: "#6ec5ff",
    cover: ""
  },
  {
    slug: "liquid-death",
    date: "2026-07-12",
    brand: "Liquid Death",
    category: "饮料消费品",
    market: "美国 / 英国",
    tags: ["娱乐化品牌", "会员积分", "零售放大"],
    summary: "Liquid Death 没把水讲成更纯净的健康任务，而是先用重金属视觉、恶搞内容、merch、Skulls 积分、Amazon 补货、场馆合作和大零售铺货，把最无聊的饮用品类改写成一个能被讨论、被拿在手里、也能被持续复购的娱乐消费品牌。",
    insight: "越基础、越同质化的品类，越要先重写品类语气，再把官网、会员、零售和补货链路接成同一个世界观。",
    report: "reports/2026-07-12-liquid-death.html",
    accent: "#ff5a3d",
    cover: ""
  },
  {
    slug: "dr-squatch",
    date: "2026-07-10",
    brand: "Dr. Squatch",
    category: "个护消费品",
    market: "美国",
    tags: ["幽默创意", "订阅承接", "零售扩张"],
    summary: "Dr. Squatch 没把男士个护讲成一堂成分课，而是先用粗犷香型、夸张幽默、创作者段子、Starter Bundle、灵活订阅和零售扩张，把原本低参与的洗澡动作改写成更愿意尝试、送礼、讨论和复购的日常娱乐系统。",
    insight: "低参与品类破圈，先别教育用户变专业，先把他愿意开口谈、愿意试一次的入口做出来。",
    report: "reports/2026-07-10-dr-squatch.html",
    accent: "#8cc36f",
    cover: ""
  },
  {
    slug: "beis",
    date: "2026-07-08",
    brand: "BÉIS",
    category: "旅行用品",
    market: "美国",
    tags: ["功能演示", "创作者脚本", "零售分工"],
    summary: "BÉIS 没有把行李箱讲成更贵的专业装备，而是先抓住超重、鞋衣混装、随身包难挂和短途出行收纳混乱这些高频狼狈时刻，再用产品细节、Founder demo、pack-with-me 内容、快闪体验和 DTC/零售分工，把旅行用品做成更省脑也更愿意分享的出发系统。",
    insight: "高客单功能品要想破圈，先把用户最狼狈的 10 秒钟做成一眼能懂的解决方案，再让内容和渠道围绕它放大。",
    report: "reports/2026-07-08-beis.html",
    accent: "#f2c66d",
    cover: ""
  },
  {
    slug: "our-place",
    date: "2026-07-07",
    brand: "Our Place",
    category: "家居厨具",
    market: "美国",
    tags: ["英雄 SKU", "生活方式内容", "零售分工"],
    summary: "Our Place 没有把厨具讲成一整套专业配置，而是先用 Always Pan 这样的英雄单品压缩选择负担，再用色彩审美、菜谱内容、创作者厨房、套装升级和 DTC/零售分工，把下厨翻译成更愿意开始、分享和送礼的生活方式场景。",
    insight: "复杂耐用品破圈，往往先靠一个最省脑的英雄入口，再靠内容和渠道把它扩成整套生活方式。",
    report: "reports/2026-07-07-our-place.html",
    accent: "#e78d63",
    cover: ""
  },
  {
    slug: "blueland",
    date: "2026-07-06",
    brand: "Blueland",
    category: "家居清洁",
    market: "美国",
    tags: ["补充装系统", "环保转译", "零售放大"],
    summary: "Blueland 没有把环保清洁讲成牺牲与责任，而是用可重复使用的 Forever 瓶、补充片、套装承接、创作者推荐和 Target 放大，把“少用一次性塑料”翻译成更省脑、更顺手、也更容易坚持的家庭清洁习惯。",
    insight: "可持续品牌要想破圈，关键不是把理念讲得更重，而是把切换动作做得更轻、更默认。",
    report: "reports/2026-07-06-blueland.html",
    accent: "#6acfc7",
    cover: ""
  },
  {
    slug: "air-up",
    date: "2026-07-05",
    brand: "air up",
    category: "智能水具",
    market: "德国 / 英国 / 美国",
    tags: ["感官创新", "创作者种草", "全渠道习惯"],
    summary: "air up 没有把喝水讲成自律任务，而是用气味驱动的“有味白水”、反应型创作者内容、Starter Set 承接和零售铺货，把原本无聊的补水行为改造成更容易尝试、分享和复购的日常习惯。",
    insight: "当品类教育成本过高时，先把体验做成愿意试和愿意晒的行为，再用渠道把新奇感沉淀成习惯。",
    report: "reports/2026-07-05-air-up.html",
    accent: "#66d6df",
    cover: ""
  },
  {
    slug: "olipop",
    date: "2026-07-03",
    brand: "OLIPOP",
    category: "功能饮料",
    market: "美国",
    tags: ["怀旧口味", "创作者营销", "零售放大"],
    summary: "OLIPOP 没有把功能汽水讲成营养课，而是先保留怀旧口味、好看包装和想喝汽水的快乐，再用低糖高纤、创作者内容、订阅和零售覆盖把“更好替代”做成更容易试也更容易顺手买的日常选择。",
    insight: "更好替代型品牌要先守住原品类的快乐，再把功能、渠道和归因围绕这层快乐重组。",
    report: "reports/2026-07-03-olipop.html",
    accent: "#ff935c",
    cover: ""
  },
  {
    slug: "wild",
    date: "2026-07-02",
    brand: "Wild",
    category: "个护消费品",
    market: "英国 / 美国",
    tags: ["可持续包装", "订阅补货", "零售放大"],
    summary: "Wild 没有先把环保讲成责任，而是先把除臭剂做成愿意摆出来的生活方式配件，再用可换香型的 refill、可调订阅、联名内容和 Target 渠道把减塑行为变成更顺手的日常习惯。",
    insight: "可持续品牌破圈，往往不是靠说服用户牺牲，而是把更好的行为包装成更想要的升级体验。",
    report: "reports/2026-07-02-wild.html",
    accent: "#88d498",
    cover: ""
  },
  {
    slug: "hismile",
    date: "2026-07-01",
    brand: "Hismile",
    category: "口腔护理",
    market: "澳大利亚 / 全球",
    tags: ["感官重写", "联名内容", "套装承接"],
    summary: "Hismile 没有先把牙膏讲得更专业，而是用口味、颜色、联名和可拍的功效演示让用户愿意讨论刷牙，再用 V34、PAP+ 与 Starter Bundle 把尝鲜引向稳定的例行程序。",
    insight: "低参与度品类的增长，常常先来自更低的体验进入门槛，而不是更强的专业教育。",
    report: "reports/2026-07-01-hismile.html",
    accent: "#ff6aa7",
    cover: ""
  },
  {
    slug: "graza",
    date: "2026-06-30",
    brand: "Graza",
    category: "食品消费品",
    market: "美国",
    tags: ["场景命名", "包装创新", "创作者冷启动"],
    summary: "把复杂的橄榄油品质知识压缩成 Sizzle 与 Drizzle 两个厨房动作，再让挤压瓶同时承担使用体验、货架识别、短视频露出与补充装复购。",
    insight: "成熟品类的创新，常常不是增加知识，而是把选择压缩成一个直觉动作。",
    report: "reports/2026-06-30-graza.html",
    accent: "#d7ff45",
    cover: ""
  },
  {
    slug: "the-farmers-dog",
    date: "2026-06-29",
    brand: "The Farmer's Dog",
    category: "宠物鲜食",
    market: "美国",
    tags: ["DTC", "订阅制", "信任系统"],
    summary: "把鲜食的价格、冷链与换粮门槛拆成问卷、预分装、配送和生命周期触达，让“信任”成为产品的一部分。",
    insight: "高客单订阅的核心不是一次说服，而是持续降低每个履约节点的不确定感。",
    report: "reports/2026-06-29-the-farmers-dog.html",
    accent: "#f25f3a",
    cover: ""
  },
  {
    slug: "loop-earplugs",
    date: "2026-06-29",
    brand: "Loop Earplugs",
    category: "听力保护",
    market: "欧美",
    tags: ["场景重构", "创作者营销", "配件化"],
    summary: "把“隔绝噪音”改写成“留在现场”：用场景化声学产品、可识别耳饰造型和创作者测试闭环，把健康防护用品做成日常配件。",
    insight: "功能品破圈，常常从重新定义用户愿意公开表达的使用场景开始。",
    report: "reports/2026-06-29-loop-earplugs.html",
    accent: "#16a085",
    cover: ""
  },
  {
    slug: "owala",
    date: "2026-06-27",
    brand: "Owala",
    category: "保温水杯",
    market: "美国",
    tags: ["产品创新", "限量发售", "渠道独占"],
    summary: "用 FreeSip 消除“吸或灌”的行为冲突，再以配色、限量 Drop 和渠道独占，把耐用品变成身份配件。",
    insight: "固定英雄 SKU，用颜色与命名制造持续上新的理由。",
    report: "reports/2026-06-27-owala.html",
    accent: "#3478f6",
    cover: ""
  },
  {
    slug: "momcozy",
    date: "2026-06-26",
    brand: "Momcozy",
    category: "母婴护理",
    market: "欧美",
    tags: ["痛点创新", "KOC", "全渠道"],
    summary: "把吸奶器从医疗器械翻译成职场妈妈的自由感、隐私感和被理解感，并用真实妈妈内容建立信任。",
    insight: "不要先讲参数，先把功能翻译成用户重新获得的一段生活。",
    report: "reports/2026-06-26-momcozy.html",
    accent: "#d34f7a",
    cover: ""
  },
  {
    slug: "pop-mart",
    date: "2026-06-26",
    brand: "POP MART",
    category: "潮玩 IP",
    market: "全球",
    tags: ["IP", "稀缺感", "线下零售"],
    summary: "用 IP 稀缺感、社媒可晒性、线下仪式和全球履约，把小额潮玩做成跨市场情绪消费系统。",
    insight: "IP 的增长不只来自角色内容，还来自可重复参与的购买仪式。",
    report: "reports/2026-06-26-pop-mart.html",
    accent: "#ef3f55",
    cover: ""
  }
];
