window.BRAND_CASES = [
  {
    slug: "olipop",
    date: "2026-07-03",
    brand: "OLIPOP",
    category: "功能饮料",
    market: "美国",
    tags: ["怀旧口味", "创作者营销", "零售放大"],
    summary: "OLIPOP 没有把功能汽水讲成营养课，而是先保留怀旧口味、好看包装和想喝汽水的快乐，再用低糖高纤、创作者内容、订阅和零售覆盖把“更好替代”做成更容易试也更容易顺手买的日常选择。",
    insight: "更好替代型品牌要先守住原品类的快乐，再把功能、渠道和归因围绕这层快乐重组。",
    report: "reports/2026-07-03-olipop.html",
    accent: "#ff935c",
    cover: ""
  },
  {
    slug: "wild",
    date: "2026-07-02",
    brand: "Wild",
    category: "个护消费品",
    market: "英国 / 美国",
    tags: ["可持续包装", "订阅补货", "零售放大"],
    summary: "Wild 没有先把环保讲成责任，而是先把除臭剂做成愿意摆出来的生活方式配件，再用可换香型的 refill、可调订阅、联名内容和 Target 渠道把减塑行为变成更顺手的日常习惯。",
    insight: "可持续品牌破圈，往往不是靠说服用户牺牲，而是把更好的行为包装成更想要的升级体验。",
    report: "reports/2026-07-02-wild.html",
    accent: "#88d498",
    cover: ""
  },
  {
    slug: "hismile",
    date: "2026-07-01",
    brand: "Hismile",
    category: "口腔护理",
    market: "澳大利亚 / 全球",
    tags: ["感官重写", "联名内容", "套装承接"],
    summary: "Hismile 没有先把牙膏讲得更专业，而是用口味、颜色、联名和可拍的功效演示让用户愿意讨论刷牙，再用 V34、PAP+ 与 Starter Bundle 把尝鲜引向稳定的例行程序。",
    insight: "低参与度品类的增长，常常先来自更低的体验进入门槛，而不是更强的专业教育。",
    report: "reports/2026-07-01-hismile.html",
    accent: "#ff6aa7",
    cover: ""
  },
  {
    slug: "graza",
    date: "2026-06-30",
    brand: "Graza",
    category: "食品消费品",
    market: "美国",
    tags: ["场景命名", "包装创新", "创作者冷启动"],
    summary: "把复杂的橄榄油品质知识压缩成 Sizzle 与 Drizzle 两个厨房动作，再让挤压瓶同时承担使用体验、货架识别、短视频露出与补充装复购。",
    insight: "成熟品类的创新，常常不是增加知识，而是把选择压缩成一个直觉动作。",
    report: "reports/2026-06-30-graza.html",
    accent: "#d7ff45",
    cover: ""
  },
  {
    slug: "the-farmers-dog",
    date: "2026-06-29",
    brand: "The Farmer's Dog",
    category: "宠物鲜食",
    market: "美国",
    tags: ["DTC", "订阅制", "信任系统"],
    summary: "把鲜食的价格、冷链与换粮门槛拆成问卷、预分装、配送和生命周期触达，让“信任”成为产品的一部分。",
    insight: "高客单订阅的核心不是一次说服，而是持续降低每个履约节点的不确定感。",
    report: "reports/2026-06-29-the-farmers-dog.html",
    accent: "#f25f3a",
    cover: ""
  },
  {
    slug: "loop-earplugs",
    date: "2026-06-29",
    brand: "Loop Earplugs",
    category: "听力保护",
    market: "欧美",
    tags: ["场景重构", "创作者营销", "配件化"],
    summary: "把“隔绝噪音”改写成“留在现场”：用场景化声学产品、可识别耳饰造型和创作者测试闭环，把健康防护用品做成日常配件。",
    insight: "功能品破圈，常常从重新定义用户愿意公开表达的使用场景开始。",
    report: "reports/2026-06-29-loop-earplugs.html",
    accent: "#16a085",
    cover: ""
  },
  {
    slug: "owala",
    date: "2026-06-27",
    brand: "Owala",
    category: "保温水杯",
    market: "美国",
    tags: ["产品创新", "限量发售", "渠道独占"],
    summary: "用 FreeSip 消除“吸或灌”的行为冲突，再以配色、限量 Drop 和渠道独占，把耐用品变成身份配件。",
    insight: "固定英雄 SKU，用颜色与命名制造持续上新的理由。",
    report: "reports/2026-06-27-owala.html",
    accent: "#3478f6",
    cover: ""
  },
  {
    slug: "momcozy",
    date: "2026-06-26",
    brand: "Momcozy",
    category: "母婴护理",
    market: "欧美",
    tags: ["痛点创新", "KOC", "全渠道"],
    summary: "把吸奶器从医疗器械翻译成职场妈妈的自由感、隐私感和被理解感，并用真实妈妈内容建立信任。",
    insight: "不要先讲参数，先把功能翻译成用户重新获得的一段生活。",
    report: "reports/2026-06-26-momcozy.html",
    accent: "#d34f7a",
    cover: ""
  },
  {
    slug: "pop-mart",
    date: "2026-06-26",
    brand: "POP MART",
    category: "潮玩 IP",
    market: "全球",
    tags: ["IP", "稀缺感", "线下零售"],
    summary: "用 IP 稀缺感、社媒可晒性、线下仪式和全球履约，把小额潮玩做成跨市场情绪消费系统。",
    insight: "IP 的增长不只来自角色内容，还来自可重复参与的购买仪式。",
    report: "reports/2026-06-26-pop-mart.html",
    accent: "#ef3f55",
    cover: ""
  }
];
